# Generated by Django 4.1.5 on 2023-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacilityName', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('ContactNumber', models.CharField(blank=True, max_length=255)),
                ('Country', models.CharField(blank=True, max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Plan', models.CharField(blank=True, max_length=255)),
                ('PresonName', models.CharField(max_length=255)),
            ],
        ),
    ]
